-- init.sql
CREATE TABLE firefighters (
    firefighter_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    pesel CHAR(11),
    phone CHAR(12),
    account_number CHAR(26),
    email VARCHAR(255)
);

CREATE TABLE trainings (
    training_id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TYPE training_status AS ENUM ('VALID', 'INVALID');

CREATE TABLE firefighter_training (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firefighter_id INT NOT NULL REFERENCES firefighters(firefighter_id),
    training_id VARCHAR(255) NOT NULL REFERENCES trainings(training_id),
    date DATE NOT NULL,
    expiration DATE,
    status training_status DEFAULT 'VALID'
);

CREATE TYPE examination_type AS ENUM ('FIREFIGHTER', 'DRIVER');

CREATE TABLE medical_examinations (
    examination_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    examination_type examination_type DEFAULT 'FIREFIGHTER' NOT NULL,
    firefighter_id INT NOT NULL REFERENCES firefighters(firefighter_id),
    date DATE NOT NULL,
    expiration DATE NOT NULL
);

CREATE TABLE banks (
    bank_id CHAR(4) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL
);
