INSERT INTO trainings (training_id, name) VALUES
('BHP', 'Bezpieczeństwo i Higiena Pracy'),
('ODO', 'Szkolenie obsługi sprzętu ochrony dróg oddechowych'),
('OSP_P1', 'Szkolenie strażaków ratowników OSP część I'),
('OSP_P2', 'Szkolenie strażaków ratowników OSP część II'),
('OSP', 'Szkolenie strażaków ratowników OSP kurs jednolity'),
('POD_1', 'Szkolenie podstawowe strażaków ratowników OSP (po 2015)'),
('KOM_DYM', 'Szkolenie strażaków ratowników OSP w komorze dymowej'),
('KPP', 'Szkolenie z zakresu kwalifikowanej pierwszej pomocy wg rozporządzenia MSWiA oraz MON'),
('KPP_E', 'Egzamin potwierdzający uprawnienia w zakresie kwalifikowanej pierwszej pomocy wg rozporządzenia MSWiA oraz MON'),
('KON_SER', 'Szkolenie kierowców konserwatorów sprzętu ratowniczego OSP'),
('TECH', 'Szkolenie z zakresu ratownictwa technicznego dla strażaków ratowników OSP'),
('PRZECIW', 'Szkolenie strażaków ratowników OSP z zakresu działań przeciwpowodziowych oraz ratownictwa na wodach'),
('DOW_1', 'Szkolenie dowódców OSP'),
('NACZ_1', 'Szkolenie naczelników OSP'),
('KOM_GM', 'Szkolenie komendantów gminnych Związku Ochotniczych Straży Pożarnych RP'),
('SZR_2006', 'Szkolenie szeregowców OSP (przed 11.05.2006)'),
('DOW_2006', 'Szkolenie dowódców OSP (przed 11.05.2006)'),
('NACZ_2006', 'Szkolenie naczelników OSP (przed 11.05.2006)'),
('OPR_2006', 'Szkolenie operatorów sprzętu OSP (przed 11.05.2006)'),
('KIER_C', 'Kierowca pojazdów uprzywilejowanych C'),
('KIER_B', 'Kierowca pojazdów uprzywilejowanych B'),
('CHEM', 'Szkolenie w zakresie ratownictwa chemicznego i ekologicznego'),
('WYS', 'Szkolenie z zakresu ratownictwa wysokościowego'),
('BSP_A1_3', 'Szkolenie pilota BSP - A1/A3'),
('BSP_A2', 'Szkolenie pilota BSP - A2'),
('BSP_INNE', 'Szkolenie pilota BSP - Inne'),
('BSP_NSTS01', 'Szkolenie pilota BSP - NSTS01'),
('BSP_NSTS02', 'Szkolenie pilota BSP - NSTS02'),
('BSP_NSTS03', 'Szkolenie pilota BSP - NSTS03'),
('BSP_NSTS04', 'Szkolenie pilota BSP - NSTS04'),
('BSP_NSTS05', 'Szkolenie pilota BSP - NSTS05'),
('BSP_NSTS06', 'Szkolenie pilota BSP - NSTS06'),
('BSP_NSTS07', 'Szkolenie pilota BSP - NSTS07'),
('BSP_NSTS08', 'Szkolenie pilota BSP - NSTS08'),
('BSP_NSTS09', 'Szkolenie pilota BSP - NSTS09'),
('BSP_STS01', 'Szkolenie pilota BSP - STS01'),
('BSP_STS02', 'Szkolenie pilota BSP - STS02'),
('DRABINA', 'Szkolenie w zakresie eksploatacji, obsługi i konserwacji samochodów z drabiną mechaniczną'),
('PODNOSNIK', 'Szkolenie w zakresie eksploatacji, obsługi i konserwacji samochodów z podnośnikiem'),
('WODA', 'Szkolenie w zakresie ratownictwa wodnego'),
('POSZUK', 'Szkolenie dla grup poszukiwawczo-ratowniczych'),
('RUCH', 'Szkolenie z zakresu kierowania ruchem drogowym'),
('LPR', 'Szkolenie z zakresu przyjmowania śmigłowca LPR'),
('RAT_MED', 'Ratownik medyczny'),
('UKF', 'Zasady pracy w radiowej sieci UKF PSP'),
('STERNIK', 'Kurs specjalistyczny sterników motorowodnych'),
('STERMOT', 'Kurs specjalistyczny stermotorzystów'),
('DRWAL', 'Kurs drwala pilarza'),
('PILARKA', 'Kurs operatora pilarek'),
('ZBIORNIKI', 'Kurs specjalistyczny napełniania zbiorników ciśnieniowych');